/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-tool-registry.ts
 *
 * To regenerate: npm run generate:tools
 */

import type { ToolFunction } from '../domain/entities/Tool.js';

import { executeJavaScript } from './code/executeJavaScript.js';
import { customToolDelete } from './custom-tools/customToolDelete.js';
import { customToolDraft } from './custom-tools/customToolDraft.js';
import { customToolList } from './custom-tools/customToolList.js';
import { customToolLoad } from './custom-tools/customToolLoad.js';
import { customToolSave } from './custom-tools/customToolSave.js';
import { customToolTest } from './custom-tools/customToolTest.js';
import { desktopGetCursor } from './desktop/getCursor.js';
import { desktopGetScreenSize } from './desktop/getScreenSize.js';
import { desktopKeyboardKey } from './desktop/keyboardKey.js';
import { desktopKeyboardType } from './desktop/keyboardType.js';
import { desktopMouseClick } from './desktop/mouseClick.js';
import { desktopMouseDrag } from './desktop/mouseDrag.js';
import { desktopMouseMove } from './desktop/mouseMove.js';
import { desktopMouseScroll } from './desktop/mouseScroll.js';
import { desktopScreenshot } from './desktop/screenshot.js';
import { desktopWindowFocus } from './desktop/windowFocus.js';
import { desktopWindowList } from './desktop/windowList.js';
import { editFile } from './filesystem/editFile.js';
import { glob } from './filesystem/glob.js';
import { grep } from './filesystem/grep.js';
import { listDirectory } from './filesystem/listDirectory.js';
import { readFile } from './filesystem/readFile.js';
import { writeFile } from './filesystem/writeFile.js';
import { jsonManipulator } from './json/jsonManipulator.js';
import { generateRoutine } from './routines/generateRoutine.js';
import { routineDelete } from './routines/routineDelete.js';
import { routineGet } from './routines/routineGet.js';
import { routineGetTaskSteps } from './routines/routineGetTaskSteps.js';
import { routineList } from './routines/routineList.js';
import { routineListExecutions } from './routines/routineListExecutions.js';
import { routineUpdate } from './routines/routineUpdate.js';
import { routineUpdateTask } from './routines/routineUpdateTask.js';
import { bash } from './shell/bash.js';
import { bgProcessKill } from './shell/bgProcessKill.js';
import { bgProcessList } from './shell/bgProcessList.js';
import { bgProcessOutput } from './shell/bgProcessOutput.js';
import { devServer } from './shell/devServer.js';
import { webFetch } from './web/webFetch.js';

/** Tool category for grouping */
export type ToolCategory = 'filesystem' | 'shell' | 'web' | 'code' | 'json' | 'connector' | 'desktop' | 'custom-tools' | 'routines' | 'other';

/** Metadata for a tool in the registry */
export interface ToolRegistryEntry {
  /** Tool name (matches definition.function.name) */
  name: string;
  /** Export variable name */
  exportName: string;
  /** Human-readable display name */
  displayName: string;
  /** Category for grouping */
  category: ToolCategory;
  /** Brief description */
  description: string;
  /** The actual tool function */
  tool: ToolFunction;
  /** Whether this tool is safe without explicit approval */
  safeByDefault: boolean;
  /** SHA-256 fingerprint of the tool source and its OneRingAI runtime source. */
  implementationHash?: string;
  /** Whether this tool requires a connector */
  requiresConnector?: boolean;
  /** Supported connector service types (if requiresConnector) */
  connectorServiceTypes?: string[];
}

/** Complete registry of all built-in tools */
export const toolRegistry: ToolRegistryEntry[] = [
  {
    name: 'execute_javascript',
    exportName: 'executeJavaScript',
    displayName: 'Execute Javascript',
    category: 'code',
    description: "Execute JavaScript code in a secure sandbox with authenticated API access via connectors.",
    tool: executeJavaScript,
    safeByDefault: false,
    implementationHash: 'sha256:778048bceb1d9d81236856e7c493df5b42c9daebb384927c77e111b78002b645',
  },
  {
    name: 'custom_tool_delete',
    exportName: 'customToolDelete',
    displayName: 'Custom Tool Delete',
    category: 'custom-tools',
    description: "Delete a custom tool from persistent storage.",
    tool: customToolDelete,
    safeByDefault: false,
    implementationHash: 'sha256:e197478cf469eeb108d95a53d703a64c59ad2eec7ed4671f9114eabde61634da',
  },
  {
    name: 'custom_tool_draft',
    exportName: 'customToolDraft',
    displayName: 'Custom Tool Draft',
    category: 'custom-tools',
    description: "Validate a draft custom tool definition. Checks name format, schema structure, and code syntax.",
    tool: customToolDraft,
    safeByDefault: true,
    implementationHash: 'sha256:7c9099e795a7db76b0391176a3f2133cf4fb7d720a27256d0681aac458753bb9',
  },
  {
    name: 'custom_tool_list',
    exportName: 'customToolList',
    displayName: 'Custom Tool List',
    category: 'custom-tools',
    description: "List saved custom tools from persistent storage. Supports filtering by search text, tags, and category.",
    tool: customToolList,
    safeByDefault: true,
    implementationHash: 'sha256:e50b0d59214eb6e9ad02e41ae97d8a1bd569fb4bca2a01241458999fe2112ba7',
  },
  {
    name: 'custom_tool_load',
    exportName: 'customToolLoad',
    displayName: 'Custom Tool Load',
    category: 'custom-tools',
    description: "Load a full custom tool definition from storage (including code).",
    tool: customToolLoad,
    safeByDefault: true,
    implementationHash: 'sha256:2eee9953a50197c2c6c30f29b67b3e061c6f3b8fa6e9c22caeb863328bb4ae02',
  },
  {
    name: 'custom_tool_save',
    exportName: 'customToolSave',
    displayName: 'Custom Tool Save',
    category: 'custom-tools',
    description: "Save a custom tool definition to persistent storage.",
    tool: customToolSave,
    safeByDefault: false,
    implementationHash: 'sha256:5df43d0db5d16f58de534edd21a620a582adf6ed4d00c02f6d321d41d614f41e',
  },
  {
    name: 'custom_tool_test',
    exportName: 'customToolTest',
    displayName: 'Custom Tool Test',
    category: 'custom-tools',
    description: "Test custom tool code by executing it in the VM sandbox with provided test input.",
    tool: customToolTest,
    safeByDefault: false,
    implementationHash: 'sha256:b5fb6b0a54ec6a1214c59a86d02b39501efc7d75bd303d8353bfe974d06d0caa',
  },
  {
    name: 'desktop_get_cursor',
    exportName: 'desktopGetCursor',
    displayName: 'Desktop Get Cursor',
    category: 'desktop',
    description: "Get the current mouse cursor position in screen pixel coordinates (same space as the screenshot and mouseClick/mouseMove).",
    tool: desktopGetCursor,
    safeByDefault: false,
    implementationHash: 'sha256:3a560ca24e2e7ea9d1246fbc9e28a5021f5bedc50fbde552b2556eca13631223',
  },
  {
    name: 'desktop_get_screen_size',
    exportName: 'desktopGetScreenSize',
    displayName: 'Desktop Get Screen Size',
    category: 'desktop',
    description: "Get the screen dimensions. Returns physical pixel size (screenshot space), logical size (OS coordinates), and the scale factor (e.g., 2.0 on Retina displays). All desktop tool coordinates use physical",
    tool: desktopGetScreenSize,
    safeByDefault: false,
    implementationHash: 'sha256:570cc04f7007b71717a3ec5d780982f532e6e60683bb128c14fa652b8e0910f3',
  },
  {
    name: 'desktop_keyboard_key',
    exportName: 'desktopKeyboardKey',
    displayName: 'Desktop Keyboard Key',
    category: 'desktop',
    description: "Press a keyboard shortcut or special key. Use \"+\" to combine keys (e.g., \"ctrl+c\", \"cmd+shift+s\", \"enter\", \"tab\", \"escape\"). Modifiers: ctrl, cmd/command, alt/option, shift. Special keys: enter, tab, ",
    tool: desktopKeyboardKey,
    safeByDefault: false,
    implementationHash: 'sha256:5d961cb73daadce2ed9b15fb8771d2b9032ff191b9c5d5f06ce7a201812e8372',
  },
  {
    name: 'desktop_keyboard_type',
    exportName: 'desktopKeyboardType',
    displayName: 'Desktop Keyboard Type',
    category: 'desktop',
    description: "Type text using the keyboard. Each character is typed as a keypress. Use this for entering text into focused input fields.",
    tool: desktopKeyboardType,
    safeByDefault: false,
    implementationHash: 'sha256:78467797d3a100b45f32738a6ff039484cb0b78303a93a9a8d98d8c4747319db',
  },
  {
    name: 'desktop_mouse_click',
    exportName: 'desktopMouseClick',
    displayName: 'Desktop Mouse Click',
    category: 'desktop',
    description: "Click the mouse at the specified position or at the current cursor position. Supports left/right/middle button and single/double/triple click.",
    tool: desktopMouseClick,
    safeByDefault: false,
    implementationHash: 'sha256:29f4fa517e2e5f90c5588c9cd813fbaf34b0d18687039f2839e8e2475dc870b1',
  },
  {
    name: 'desktop_mouse_drag',
    exportName: 'desktopMouseDrag',
    displayName: 'Desktop Mouse Drag',
    category: 'desktop',
    description: "Drag the mouse from one position to another. Presses the button at the start position, moves to the end position, then releases.",
    tool: desktopMouseDrag,
    safeByDefault: false,
    implementationHash: 'sha256:5a6b270507bd3193aba5b93d0691c338cf3e45b61ad97e88898ada68e8a9fdc8',
  },
  {
    name: 'desktop_mouse_move',
    exportName: 'desktopMouseMove',
    displayName: 'Desktop Mouse Move',
    category: 'desktop',
    description: "Move the mouse cursor to the specified (x, y) position. Coordinates are in screen pixel space (full screen). Returns the actual cursor position after the move for verification.",
    tool: desktopMouseMove,
    safeByDefault: false,
    implementationHash: 'sha256:e248094ced69311ae1d6f9e34fdfeae1bd7c7b9dee8433afdff17825dc9a5caf',
  },
  {
    name: 'desktop_mouse_scroll',
    exportName: 'desktopMouseScroll',
    displayName: 'Desktop Mouse Scroll',
    category: 'desktop',
    description: "Scroll the mouse wheel. Positive deltaY scrolls down, negative scrolls up. Positive deltaX scrolls right, negative scrolls left. Optionally specify position to scroll at.",
    tool: desktopMouseScroll,
    safeByDefault: false,
    implementationHash: 'sha256:b1ae2e99fa54fc641ccfa697302c5f85ecf1f3ab8eb5bd1281d97a9c4bcf3073',
  },
  {
    name: 'desktop_screenshot',
    exportName: 'desktopScreenshot',
    displayName: 'Desktop Screenshot',
    category: 'desktop',
    description: "Take a screenshot of the entire screen or a specific region. Returns the screenshot image for visual analysis. The image pixel coordinates match the coordinate space used by desktop_mouse_click / desk",
    tool: desktopScreenshot,
    safeByDefault: false,
    implementationHash: 'sha256:1bff0d40dad0570cdd05a0426ccbe858dbea52193614a97144f01c2059112e09',
  },
  {
    name: 'desktop_window_focus',
    exportName: 'desktopWindowFocus',
    displayName: 'Desktop Window Focus',
    category: 'desktop',
    description: "Focus (bring to front) a window by its ID. Use desktop_window_list to get available window IDs.",
    tool: desktopWindowFocus,
    safeByDefault: false,
    implementationHash: 'sha256:4dd5fc517cf53600833ecdd8a46557723bb18d1cdf1a759ffc0b0fec3be3e8c1',
  },
  {
    name: 'desktop_window_list',
    exportName: 'desktopWindowList',
    displayName: 'Desktop Window List',
    category: 'desktop',
    description: "List all visible windows on the desktop. Returns window IDs, titles, application names, and bounds. Use the window ID with desktop_window_focus to bring a window to the foreground.",
    tool: desktopWindowList,
    safeByDefault: false,
    implementationHash: 'sha256:316ef095578454f9ae062846f9f5662a5520d6055c2c750015dd726252fba6cb',
  },
  {
    name: 'edit_file',
    exportName: 'editFile',
    displayName: 'Edit File',
    category: 'filesystem',
    description: "Perform exact string replacements in files.",
    tool: editFile,
    safeByDefault: false,
    implementationHash: 'sha256:dd3fa2fde9056b772a6deefb5015ed03e0b5c6ad285227b54cc6af3b1e6c3f5a',
  },
  {
    name: 'glob',
    exportName: 'glob',
    displayName: 'Glob',
    category: 'filesystem',
    description: "Fast file pattern matching tool that finds files by name patterns.",
    tool: glob,
    safeByDefault: true,
    implementationHash: 'sha256:0964618c4160350ef93da014a412e5f90978c29e5854ba649c6cdfbc57ad7feb',
  },
  {
    name: 'grep',
    exportName: 'grep',
    displayName: 'Grep',
    category: 'filesystem',
    description: "A powerful search tool for finding content within files.",
    tool: grep,
    safeByDefault: true,
    implementationHash: 'sha256:7e24b152211a2456e6fe6d87e31a0d5dca1ddb7097318b6a40da02e7e7a7d6f4',
  },
  {
    name: 'list_directory',
    exportName: 'listDirectory',
    displayName: 'List Directory',
    category: 'filesystem',
    description: "List the contents of a directory on the local filesystem.",
    tool: listDirectory,
    safeByDefault: true,
    implementationHash: 'sha256:1805a5360175021aed8b53bd87019a3b58ed2932101f59ada49931b42af94840',
  },
  {
    name: 'read_file',
    exportName: 'readFile',
    displayName: 'Read File',
    category: 'filesystem',
    description: "Read content from a file on the local filesystem. Supports text files AND binary document formats — PDF, DOCX, PPTX, XLSX, ODS, ODT, ODP, and images (PNG, JPG, GIF, WEBP) are automatically converted t",
    tool: readFile,
    safeByDefault: true,
    implementationHash: 'sha256:9434818a299192e9d2c6e2b2fe6d8eb6e4df27c25d78141162c2ee58bdfff830',
  },
  {
    name: 'write_file',
    exportName: 'writeFile',
    displayName: 'Write File',
    category: 'filesystem',
    description: "Write content to a file on the local filesystem.",
    tool: writeFile,
    safeByDefault: false,
    implementationHash: 'sha256:599d5bca4e796d16a62d3ff247280c2aa680ec87a54b5b3da4a1606fa1e082d0',
  },
  {
    name: 'json_manipulate',
    exportName: 'jsonManipulator',
    displayName: 'Json Manipulate',
    category: 'json',
    description: "Manipulate JSON objects by deleting, adding, or replacing fields at any depth.",
    tool: jsonManipulator,
    safeByDefault: true,
    implementationHash: 'sha256:49625c2ba8ac0afd31c85c828250c17379fbcb8cbeab7eb847a7585350559441',
  },
  {
    name: 'generate_routine',
    exportName: 'generateRoutine',
    displayName: 'Generate Routine',
    category: 'routines',
    description: "Complete routine definition input",
    tool: generateRoutine,
    safeByDefault: false,
    implementationHash: 'sha256:011c19df45362d070c8db1e3b5cd6701e8b6540ed697932b1f4e39c3511efe4f',
  },
  {
    name: 'routine_delete',
    exportName: 'routineDelete',
    displayName: 'Routine Delete',
    category: 'routines',
    description: "Permanently delete a routine definition. Past execution records are preserved, but any schedules or systems still referencing this routine ID will fail at runtime. Confirm with the user before calling",
    tool: routineDelete,
    safeByDefault: false,
    implementationHash: 'sha256:f628cde039b91c1168c72c3e4dfa6085ecc6bdd4e7e317e3a237a412a98ab38d',
  },
  {
    name: 'routine_get',
    exportName: 'routineGet',
    displayName: 'Routine Get',
    category: 'routines',
    description: "Retrieve a routine definition by ID or by name search. Returns the full routine structure including tasks, parameters, and metadata.",
    tool: routineGet,
    safeByDefault: false,
    implementationHash: 'sha256:59e1002d34d74b101e9123157e630af603e7357757935ba387c23118d9c3714f',
  },
  {
    name: 'routine_get_task_steps',
    exportName: 'routineGetTaskSteps',
    displayName: 'Routine Get Task Steps',
    category: 'routines',
    description: "Get step-level execution detail for a routine execution. Filter by task name, phase, or step types.\\n\\n",
    tool: routineGetTaskSteps,
    safeByDefault: false,
    implementationHash: 'sha256:dd793c052060b3113f5204a9dd5c69603fbbf2723e687dcd922e4cbb897c742e',
  },
  {
    name: 'routine_list',
    exportName: 'routineList',
    displayName: 'Routine List',
    category: 'routines',
    description: "List routine definitions accessible to the caller. Returns slim summary entries (id, name, description, version, author, tags, task count, parameter names) — fetch the full structure with routine_get.",
    tool: routineList,
    safeByDefault: false,
    implementationHash: 'sha256:acb84a0608ce67cde24c0fbcf1e181984a9be0516e96de58f5c956d2521f7261',
  },
  {
    name: 'routine_list_executions',
    exportName: 'routineListExecutions',
    displayName: 'Routine List Executions',
    category: 'routines',
    description: "List execution records for a routine. Returns summaries of past and current executions including status, timing, and per-task results.",
    tool: routineListExecutions,
    safeByDefault: false,
    implementationHash: 'sha256:848bc5010d5a089eeaa9f5559abde128e46d28847f077e6e8bf7f3683b947202',
  },
  {
    name: 'routine_update',
    exportName: 'routineUpdate',
    displayName: 'Routine Update',
    category: 'routines',
    description: "Update an existing routine definition.",
    tool: routineUpdate,
    safeByDefault: false,
    implementationHash: 'sha256:10705a81b7515c4aeab641a2d7d39045029c3d19bffc8c0a6accea9dbe886e00',
  },
  {
    name: 'routine_update_task',
    exportName: 'routineUpdateTask',
    displayName: 'Routine Update Task',
    category: 'routines',
    description: "Update a specific task within an existing routine definition. Validates the updated routine before saving.",
    tool: routineUpdateTask,
    safeByDefault: false,
    implementationHash: 'sha256:273a1f1c806e8c275d77dd6ce19ef5970a182a42fe86ab9187d07926e1d28574',
  },
  {
    name: 'bash',
    exportName: 'bash',
    displayName: 'Bash',
    category: 'shell',
    description: "Execute shell commands with optional timeout.",
    tool: bash,
    safeByDefault: false,
    implementationHash: 'sha256:894898b3f9bd86a036bc3c3775e1bbb8efe359c0784f93340153f289788e8b4b',
  },
  {
    name: 'bg_process_kill',
    exportName: 'bgProcessKill',
    displayName: 'Bg Process Kill',
    category: 'shell',
    description: "Stop a running background process. Sends SIGTERM for graceful shutdown (allows the process to clean up), then SIGKILL after 3 seconds if it hasn't exited. Kills the entire process tree — so \"npm run d",
    tool: bgProcessKill,
    safeByDefault: false,
    implementationHash: 'sha256:148f63b0ee57ac21d68352b242290aa3b3a10de49fc452c5361febbc92bb0579',
  },
  {
    name: 'bg_process_list',
    exportName: 'bgProcessList',
    displayName: 'Bg Process List',
    category: 'shell',
    description: "List all background processes and their current status. Use this to: see what background processes are running (dev servers, watchers, builds), find a process ID you forgot, check if a background comm",
    tool: bgProcessList,
    safeByDefault: true,
    implementationHash: 'sha256:1dfdbd33214576bf66f13357870afbd4a13cde315761a45662c802fa25bfc65c',
  },
  {
    name: 'bg_process_output',
    exportName: 'bgProcessOutput',
    displayName: 'Bg Process Output',
    category: 'shell',
    description: "Read output from a background process started with dev_server or bash run_in_background=true. Use this to monitor dev servers, file watchers, build processes, or any background command. For processes ",
    tool: bgProcessOutput,
    safeByDefault: true,
    implementationHash: 'sha256:8dfb9af593a860c62e44b0c87dfad76fcbaa03f0cbcc642e8c8df6cd0e848e9e',
  },
  {
    name: 'dev_server',
    exportName: 'devServer',
    displayName: 'Dev Server',
    category: 'shell',
    description: "Start a development server or long-running process with automatic log file capture.",
    tool: devServer,
    safeByDefault: false,
    implementationHash: 'sha256:0414be8b73bb619ffeec553152ab941ea7621fe0cd14e2640e49d05b6643fbe5',
  },
  {
    name: 'web_fetch',
    exportName: 'webFetch',
    displayName: 'Web Fetch',
    category: 'web',
    description: "Fetch and extract content from a URL — works with web pages AND document files (PDF, DOCX, XLSX, PPTX, etc.). Document URLs are automatically detected and converted to markdown text.",
    tool: webFetch,
    safeByDefault: true,
    implementationHash: 'sha256:8c682b570642c3ea198ccc715befcd670ef10055e34b4a2c56ab09d19d7917d1',
  }
];

/** Get all built-in tools as ToolFunction array */
export function getAllBuiltInTools(): ToolFunction[] {
  return toolRegistry.map((entry) => entry.tool);
}

/** Get full tool registry with metadata */
export function getToolRegistry(): ToolRegistryEntry[] {
  return [...toolRegistry];
}

/** Get tools by category */
export function getToolsByCategory(category: ToolCategory): ToolRegistryEntry[] {
  return toolRegistry.filter((entry) => entry.category === category);
}

/** Get tool by name */
export function getToolByName(name: string): ToolRegistryEntry | undefined {
  return toolRegistry.find((entry) => entry.name === name);
}

/** Get tools that require connector configuration */
export function getToolsRequiringConnector(): ToolRegistryEntry[] {
  return toolRegistry.filter((entry) => entry.requiresConnector);
}

/** Get all unique category names */
export function getToolCategories(): ToolCategory[] {
  return [...new Set(toolRegistry.map((entry) => entry.category))];
}
